// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateTask(arg1:dto.Task):Promise<dto.Task>;

export function DeleteTask(arg1:dto.Task):Promise<void>;

export function GetAllTasks():Promise<Array<dto.Task>>;

export function ToggleTask(arg1:dto.Task):Promise<void>;

export function UpdateTask(arg1:dto.Task):Promise<void>;
