// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';


export function CreateTask(arg1:dto.Task):Promise<dto.Task>;

export function DeleteTask(arg1:model.Task):Promise<void>;

export function GetAllTasks():Promise<Array<model.Task>>;

