// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function CreateTask(arg1:dto.Task):Promise<dto.Task>;

export function DeleteTask(arg1:dto.Task):Promise<void>;

export function GetAllTasks():Promise<Array<dto.Task>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ToggleTask(arg1:dto.Task):Promise<void>;
