// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['handler']['TaskHandler']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['handler']['TaskHandler']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['handler']['TaskHandler']['GetAllTasks']();
}

export function ToggleTask(arg1) {
  return window['go']['handler']['TaskHandler']['ToggleTask'](arg1);
}
